
import type { Metadata } from "next";
import { ClerkProvider, SignedIn, UserButton } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SyncUser from "../utils/SyncUser";
import Sidenav from "../components/navbar/Sidebar";
// import Sidebar from "../../../components/navbar/Sidebar"; // <-- Added Sidebar import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        <body>
          <div className="relative min-h-screen">
            <SignedIn>
              <div className="absolute top-4 right-4 z-50">
                <UserButton afterSignOutUrl="/" />
              </div>
            </SignedIn>
            <SyncUser />
            <Sidenav />
            <main className="pt-16 px-4">{children}</main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
